---
version: "3.3"

services:
  emulator:
    image: gcr.io/flow-container-registry/emulator:v0.22.0
    environment:
      - FLOW_SERVICEPRIVATEKEY=${ADMIN_PRIVATE_KEY}
      - FLOW_VERBOSE=true
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
      - FLOW_INTERVAL=5s
    ports:
      - "3569:3569"
      - "8080:8080"

  fcl-wallet-adapter:
    build: .
    ports:
      - 4000:3000

  wallet:
    image: gcr.io/flow-container-registry/wallet-api:v0.3.1
    ports:
      - "3000:3000"
    environment:
      - DATABASE_TYPE=psql
      - DATABASE_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - ACCESS_API_HOST=emulator:3569
      - CHAIN_ID=flow-emulator
      - ADMIN_ADDRESS=${ADMIN_ADDRESS}
      - ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
      - DEFAULT_KEY_TYPE=local
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENABLED_TOKENS=FUSD:${ADMIN_ADDRESS}:fusd,FlowToken:0x0ae53cb6e3f42a79:flow
    depends_on:
      - db
      - emulator

  example:
    container_name: fcl-adapter-example
    image: nginx:mainline-alpine
    volumes:
      - ./example:/usr/share/nginx/html
    ports:
      - "4001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
