---
version: "3.3"

services:
  emulator:
    image: gcr.io/flow-container-registry/emulator:0.24.0
    environment:
      - FLOW_SERVICEPRIVATEKEY=${ADMIN_PRIVATE_KEY}
      - FLOW_VERBOSE=true
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
      - FLOW_INTERVAL=5s
    ports:
      - "3569:3569"
      - "8080:8080"

  fcl-wallet-adapter:
    build: .
    ports:
      - 4000:3000

  wallet:
    image: ghcr.io/flow-hydraulics/flow-wallet-api:0.7.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - FLOW_WALLET_DATABASE_TYPE=psql
      - FLOW_WALLET_DATABASE_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLOW_WALLET_ACCESS_API_HOST=emulator:3569
      - FLOW_WALLET_CHAIN_ID=flow-emulator
      - FLOW_WALLET_ADMIN_ADDRESS=${ADMIN_ADDRESS}
      - FLOW_WALLET_ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
      - FLOW_WALLET_DEFAULT_KEY_TYPE=local
      - FLOW_WALLET_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FLOW_WALLET_ENABLED_TOKENS=FUSD:${ADMIN_ADDRESS}:fusd,FlowToken:0x0ae53cb6e3f42a79:flow
      - FLOW_WALLET_ADMIN_PROPOSAL_KEY_COUNT=50
    depends_on:
      - db
      - emulator

  example:
    container_name: fcl-adapter-example
    image: nginx:mainline-alpine
    volumes:
      - ./example:/usr/share/nginx/html
    ports:
      - "4001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
