---
version: "3.3"

services:
  emulator:
    image: gcr.io/flow-container-registry/emulator:0.24.0
    environment:
      - FLOW_SERVICEPRIVATEKEY=${ADMIN_PRIVATE_KEY}
      - FLOW_VERBOSE=true
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
      - FLOW_INTERVAL=5s
    ports:
      - "3569:3569"
      - "8080:8080"

  fcl-dev-wallet:
    image: ghcr.io/onflow/fcl-dev-wallet:0.1.0
    ports:
      - "8701:8701"
    environment:
      - PORT=8701
      - FLOW_ACCESS_NODE=http://emulator:8080
      - FLOW_ACCOUNT_KEY_ID=0
      - FLOW_ACCOUNT_PRIVATE_KEY=4f82df6790f07b281adb5bbc848bd6298a2de67f94bdfac7a400d5a1b893de5
      - FLOW_ACCOUNT_PUBLIC_KEY=519e9fbf966c6589fafe60903c0da5f55c5cb50aee5d870f097b35dfb6de13c170718cd92f50811cdd9290e51c2766440b696e0423a5031ae482cca79e3c479
      - FLOW_INIT_ACCOUNTS=0
      - FLOW_ACCOUNT_ADDRESS=${ADMIN_ADDRESS}
      - FLOW_AVATAR_URL=https://avatars.onflow.org/avatar/

  fcl-wallet-adapter:
    build: .
    ports:
      - 3000:3000
      - 49153:49153
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
    command: npm run dev

  wallet:
    image: ghcr.io/flow-hydraulics/flow-wallet-api:0.7.0
    restart: unless-stopped
    environment:
      - FLOW_WALLET_DATABASE_TYPE=psql
      - FLOW_WALLET_DATABASE_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLOW_WALLET_ACCESS_API_HOST=emulator:3569
      - FLOW_WALLET_CHAIN_ID=flow-emulator
      - FLOW_WALLET_ADMIN_ADDRESS=${ADMIN_ADDRESS}
      - FLOW_WALLET_ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
      - FLOW_WALLET_DEFAULT_KEY_TYPE=local
      - FLOW_WALLET_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FLOW_WALLET_ENABLED_TOKENS=FUSD:${ADMIN_ADDRESS}:fusd,FlowToken:0x0ae53cb6e3f42a79:flow
      - FLOW_WALLET_ADMIN_PROPOSAL_KEY_COUNT=50
    depends_on:
      - db
      - emulator

  example:
    container_name: fcl-adapter-example
    image: nginx:mainline-alpine
    volumes:
      - ./example:/usr/share/nginx/html
    ports:
      - "4001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
